### ISSUE TITLE
Does not work in IE11 and other Trident-based browsers

### ISSUE THREAD

**Issue by sia1984** [MarkusBauer/secretnote#1]
With Internet Explorer 11 (user agent `Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`) and earlier Trident engine browsers, the site doesn't work properly. I tested it in IE6 in WINE, too, which lead to the same behaviour.

If you create a note, IE11 opens `note/[id]?text=test` which shows the "new note" site again.

If you open a note link, IE11 shows the correct URL (including the encryption password after `#`), but the site itself is the "new note" page again.

In Microsoft Edge and all non-IE GUI browsers I tested (Firefox, Opera, new Opera, Chromium, Chrome), this works properly.

If you don't want to fix this, which I totally understand (IE is deprecated) but not recommend (IE is still used, e.g. in Japan, shitty corporations, embedded devices, nuke missile control sites, and Russia), you may at least display a warning banner.

**Comment by MarkusBauer** [comment]
Thank you for your report!

With version 1.2.1, support for Internet Explorer 11 has been added. Earlier versions will not be supported, for a variety of reasons (Angular not supporting anything <11 is the most important one). Older versions receive a warning message that their browser is not supported. 

Please be aware that Internet Explorer support might be dropped at any time. When the Angular project decides to drop support in future releases, this project will do the same. As you wrote, IE has been deprecated for some time, and I don't really care about it (nor want to spend much energy on supporting it).
